import { type RouteConfig } from "@react-router/dev/routes";

export default [
  { file: "routes/_index.tsx", index: true },
  { file: "routes/login.tsx", path: "login" },
  {
    file: "routes/_app.tsx",
    children: [
      { file: "routes/_app.dashboard.tsx", path: "dashboard" },
      { file: "routes/_app.cash-calendar.tsx", path: "cash-calendar" },
      { file: "routes/_app.fixed-monthly.tsx", path: "fixed-monthly" },
      { file: "routes/_app.credit-cards.tsx", path: "credit-cards" },
      { file: "routes/_app.dre.tsx", path: "dre" },
      { file: "routes/_app.monthly-closing.tsx", path: "monthly-closing" },
      { file: "routes/_app.ai-chat.tsx", path: "ai-chat" },
      { file: "routes/_app.budget.tsx", path: "budget" },
      { file: "routes/_app.spending-limits.tsx", path: "spending-limits" },
      { file: "routes/_app.sales.tsx", path: "sales" },
      { file: "routes/_app.goals.tsx", path: "goals" },
      { file: "routes/_app.commercial.tsx", path: "commercial" },
      { file: "routes/_app.projects.tsx", path: "projects" },
      { file: "routes/_app.service-types.tsx", path: "service-types" },
      { file: "routes/_app.reports.tsx", path: "reports" },
      { file: "routes/_app.subscription.tsx", path: "subscription" },
      { file: "routes/_app.settings.tsx", path: "settings" },
      { file: "routes/_app.report-issue.tsx", path: "report-issue" },
      { file: "routes/_app.admin.plans.tsx", path: "admin/plans" },
      { file: "routes/_app.admin.subscriptions.tsx", path: "admin/subscriptions" },
      { file: "routes/_app.admin.reports.tsx", path: "admin/reports" },
    ],
  },
  { file: "routes/api/sub.status.ts", path: "api/sub/status" },
  { file: "routes/api/sub.pix-pending.ts", path: "api/sub/pix-pending" },
  { file: "routes/api/sub.create.ts", path: "api/sub/create" },
  { file: "routes/api/sub.cancel.ts", path: "api/sub/cancel" },
  { file: "routes/api/auth.welcome.ts", path: "api/auth/welcome" },
  { file: "routes/api/reports.ts", path: "api/reports" },
  { file: "routes/api/ai.chat.ts", path: "api/ai/chat" },
  { file: "routes/api/webhooks.abacate.ts", path: "api/webhooks/abacate" },
  { file: "routes/api/admin.plans.ts", path: "api/admin/plans" },
  { file: "routes/api/admin.subscriptions.ts", path: "api/admin/subscriptions" },
  { file: "routes/api/admin.reports.ts", path: "api/admin/reports" },
  { file: "routes/api/admin.members.$uid.permissions.ts", path: "api/admin/members/:uid/permissions" },
] satisfies RouteConfig;
