// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/cash-calendar": {
    params: {};
  };
  "/fixed-monthly": {
    params: {};
  };
  "/credit-cards": {
    params: {};
  };
  "/dre": {
    params: {};
  };
  "/budget": {
    params: {};
  };
  "/spending-limits": {
    params: {};
  };
  "/sales": {
    params: {};
  };
  "/goals": {
    params: {};
  };
  "/commercial": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/service-types": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/subscription": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/report-issue": {
    params: {};
  };
  "/admin/plans": {
    params: {};
  };
  "/admin/subscriptions": {
    params: {};
  };
  "/admin/reports": {
    params: {};
  };
  "/api/sub/status": {
    params: {};
  };
  "/api/sub/pix-pending": {
    params: {};
  };
  "/api/sub/create": {
    params: {};
  };
  "/api/sub/cancel": {
    params: {};
  };
  "/api/auth/welcome": {
    params: {};
  };
  "/api/reports": {
    params: {};
  };
  "/api/ai/chat": {
    params: {};
  };
  "/api/webhooks/abacate": {
    params: {};
  };
  "/api/admin/plans": {
    params: {};
  };
  "/api/admin/subscriptions": {
    params: {};
  };
  "/api/admin/reports": {
    params: {};
  };
  "/api/admin/members/:uid/permissions": {
    params: {
      "uid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/transactions" | "/cash-calendar" | "/fixed-monthly" | "/credit-cards" | "/dre" | "/budget" | "/spending-limits" | "/sales" | "/goals" | "/commercial" | "/projects" | "/service-types" | "/reports" | "/subscription" | "/settings" | "/report-issue" | "/admin/plans" | "/admin/subscriptions" | "/admin/reports" | "/api/sub/status" | "/api/sub/pix-pending" | "/api/sub/create" | "/api/sub/cancel" | "/api/auth/welcome" | "/api/reports" | "/api/ai/chat" | "/api/webhooks/abacate" | "/api/admin/plans" | "/api/admin/subscriptions" | "/api/admin/reports" | "/api/admin/members/:uid/permissions";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/dashboard" | "/transactions" | "/cash-calendar" | "/fixed-monthly" | "/credit-cards" | "/dre" | "/budget" | "/spending-limits" | "/sales" | "/goals" | "/commercial" | "/projects" | "/service-types" | "/reports" | "/subscription" | "/settings" | "/report-issue" | "/admin/plans" | "/admin/subscriptions" | "/admin/reports";
  };
  "routes/_app.dashboard.tsx": {
    id: "routes/_app.dashboard";
    page: "/dashboard";
  };
  "routes/_app.transactions.tsx": {
    id: "routes/_app.transactions";
    page: "/transactions";
  };
  "routes/_app.cash-calendar.tsx": {
    id: "routes/_app.cash-calendar";
    page: "/cash-calendar";
  };
  "routes/_app.fixed-monthly.tsx": {
    id: "routes/_app.fixed-monthly";
    page: "/fixed-monthly";
  };
  "routes/_app.credit-cards.tsx": {
    id: "routes/_app.credit-cards";
    page: "/credit-cards";
  };
  "routes/_app.dre.tsx": {
    id: "routes/_app.dre";
    page: "/dre";
  };
  "routes/_app.budget.tsx": {
    id: "routes/_app.budget";
    page: "/budget";
  };
  "routes/_app.spending-limits.tsx": {
    id: "routes/_app.spending-limits";
    page: "/spending-limits";
  };
  "routes/_app.sales.tsx": {
    id: "routes/_app.sales";
    page: "/sales";
  };
  "routes/_app.goals.tsx": {
    id: "routes/_app.goals";
    page: "/goals";
  };
  "routes/_app.commercial.tsx": {
    id: "routes/_app.commercial";
    page: "/commercial";
  };
  "routes/_app.projects.tsx": {
    id: "routes/_app.projects";
    page: "/projects";
  };
  "routes/_app.service-types.tsx": {
    id: "routes/_app.service-types";
    page: "/service-types";
  };
  "routes/_app.reports.tsx": {
    id: "routes/_app.reports";
    page: "/reports";
  };
  "routes/_app.subscription.tsx": {
    id: "routes/_app.subscription";
    page: "/subscription";
  };
  "routes/_app.settings.tsx": {
    id: "routes/_app.settings";
    page: "/settings";
  };
  "routes/_app.report-issue.tsx": {
    id: "routes/_app.report-issue";
    page: "/report-issue";
  };
  "routes/_app.admin.plans.tsx": {
    id: "routes/_app.admin.plans";
    page: "/admin/plans";
  };
  "routes/_app.admin.subscriptions.tsx": {
    id: "routes/_app.admin.subscriptions";
    page: "/admin/subscriptions";
  };
  "routes/_app.admin.reports.tsx": {
    id: "routes/_app.admin.reports";
    page: "/admin/reports";
  };
  "routes/api/sub.status.ts": {
    id: "routes/api/sub.status";
    page: "/api/sub/status";
  };
  "routes/api/sub.pix-pending.ts": {
    id: "routes/api/sub.pix-pending";
    page: "/api/sub/pix-pending";
  };
  "routes/api/sub.create.ts": {
    id: "routes/api/sub.create";
    page: "/api/sub/create";
  };
  "routes/api/sub.cancel.ts": {
    id: "routes/api/sub.cancel";
    page: "/api/sub/cancel";
  };
  "routes/api/auth.welcome.ts": {
    id: "routes/api/auth.welcome";
    page: "/api/auth/welcome";
  };
  "routes/api/reports.ts": {
    id: "routes/api/reports";
    page: "/api/reports";
  };
  "routes/api/ai.chat.ts": {
    id: "routes/api/ai.chat";
    page: "/api/ai/chat";
  };
  "routes/api/webhooks.abacate.ts": {
    id: "routes/api/webhooks.abacate";
    page: "/api/webhooks/abacate";
  };
  "routes/api/admin.plans.ts": {
    id: "routes/api/admin.plans";
    page: "/api/admin/plans";
  };
  "routes/api/admin.subscriptions.ts": {
    id: "routes/api/admin.subscriptions";
    page: "/api/admin/subscriptions";
  };
  "routes/api/admin.reports.ts": {
    id: "routes/api/admin.reports";
    page: "/api/admin/reports";
  };
  "routes/api/admin.members.$uid.permissions.ts": {
    id: "routes/api/admin.members.$uid.permissions";
    page: "/api/admin/members/:uid/permissions";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.dashboard": typeof import("./app/routes/_app.dashboard.tsx");
  "routes/_app.transactions": typeof import("./app/routes/_app.transactions.tsx");
  "routes/_app.cash-calendar": typeof import("./app/routes/_app.cash-calendar.tsx");
  "routes/_app.fixed-monthly": typeof import("./app/routes/_app.fixed-monthly.tsx");
  "routes/_app.credit-cards": typeof import("./app/routes/_app.credit-cards.tsx");
  "routes/_app.dre": typeof import("./app/routes/_app.dre.tsx");
  "routes/_app.budget": typeof import("./app/routes/_app.budget.tsx");
  "routes/_app.spending-limits": typeof import("./app/routes/_app.spending-limits.tsx");
  "routes/_app.sales": typeof import("./app/routes/_app.sales.tsx");
  "routes/_app.goals": typeof import("./app/routes/_app.goals.tsx");
  "routes/_app.commercial": typeof import("./app/routes/_app.commercial.tsx");
  "routes/_app.projects": typeof import("./app/routes/_app.projects.tsx");
  "routes/_app.service-types": typeof import("./app/routes/_app.service-types.tsx");
  "routes/_app.reports": typeof import("./app/routes/_app.reports.tsx");
  "routes/_app.subscription": typeof import("./app/routes/_app.subscription.tsx");
  "routes/_app.settings": typeof import("./app/routes/_app.settings.tsx");
  "routes/_app.report-issue": typeof import("./app/routes/_app.report-issue.tsx");
  "routes/_app.admin.plans": typeof import("./app/routes/_app.admin.plans.tsx");
  "routes/_app.admin.subscriptions": typeof import("./app/routes/_app.admin.subscriptions.tsx");
  "routes/_app.admin.reports": typeof import("./app/routes/_app.admin.reports.tsx");
  "routes/api/sub.status": typeof import("./app/routes/api/sub.status.ts");
  "routes/api/sub.pix-pending": typeof import("./app/routes/api/sub.pix-pending.ts");
  "routes/api/sub.create": typeof import("./app/routes/api/sub.create.ts");
  "routes/api/sub.cancel": typeof import("./app/routes/api/sub.cancel.ts");
  "routes/api/auth.welcome": typeof import("./app/routes/api/auth.welcome.ts");
  "routes/api/reports": typeof import("./app/routes/api/reports.ts");
  "routes/api/ai.chat": typeof import("./app/routes/api/ai.chat.ts");
  "routes/api/webhooks.abacate": typeof import("./app/routes/api/webhooks.abacate.ts");
  "routes/api/admin.plans": typeof import("./app/routes/api/admin.plans.ts");
  "routes/api/admin.subscriptions": typeof import("./app/routes/api/admin.subscriptions.ts");
  "routes/api/admin.reports": typeof import("./app/routes/api/admin.reports.ts");
  "routes/api/admin.members.$uid.permissions": typeof import("./app/routes/api/admin.members.$uid.permissions.ts");
};